import 'dart:io';
import 'package:csv/csv.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import '../app_state.dart';
import 'shell_screen.dart';

String money(Object? v) => 'Rs. ${NumberFormat('#,##0.00').format((v as num?) ?? 0)}';
String iso(DateTime d) => DateFormat('yyyy-MM-dd').format(d);
double number(String s) => double.tryParse(s.replaceAll(',', '')) ?? 0;

class DashboardPage extends StatefulWidget { const DashboardPage({super.key}); @override State<DashboardPage> createState() => _DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage> {
  late Future<Map<String, Object?>> data;
  @override void initState() { super.initState(); data = context.read<AppState>().repo.dashboard(); }
  @override Widget build(BuildContext context) => PageFrame(title: 'Dashboard', subtitle: DateFormat('EEEE, dd MMMM yyyy').format(DateTime.now()), actions: [IconButton(onPressed: () => setState(() => data = context.read<AppState>().repo.dashboard()), icon: const Icon(Icons.refresh))], child: FutureBuilder<Map<String, Object?>>(future: data, builder: (_, s) {
    if (!s.hasData) return const Center(child: CircularProgressIndicator()); final d = s.data!; final recent = d['recent'] as List<Map<String,Object?>>;
    return ListView(children: [Wrap(spacing: 14, runSpacing: 14, children: [
      Metric('Today’s collection', money(d['today']), Icons.payments, Colors.green), Metric('Outstanding', money(d['outstanding']), Icons.warning_amber, Colors.orange), Metric('Active students', '${d['students']}', Icons.school, Colors.blue), Metric('Active vehicles', '${d['vehicles']}', Icons.directions_bus, Colors.purple), Metric('Today’s trips', '${d['trips']}', Icons.route, Colors.teal),
    ]), const SizedBox(height: 22), Card(child: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Recent payments', style: TextStyle(fontSize: 18,fontWeight: FontWeight.bold)), const SizedBox(height: 12), if(recent.isEmpty) const SizedBox(height:150,child:EmptyState(Icons.receipt_long,'No payments yet')) else ...recent.map((r)=>ListTile(contentPadding:EdgeInsets.zero,leading:const CircleAvatar(child:Icon(Icons.check)),title:Text('${r['name']}  •  ${r['student_code']}'),subtitle:Text('${r['receipt_number']}  |  ${r['payment_date']}'),trailing:Text(money(r['amount']),style:const TextStyle(fontWeight:FontWeight.bold))))]))),
    ]);
  }));
}

class Metric extends StatelessWidget { final String label,value; final IconData icon; final Color color; const Metric(this.label,this.value,this.icon,this.color,{super.key}); @override Widget build(BuildContext context)=>SizedBox(width:220,height:122,child:Card(child:Padding(padding:const EdgeInsets.all(17),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[CircleAvatar(radius:18,backgroundColor:color.withValues(alpha:.12),child:Icon(icon,color:color,size:20)),const Spacer(),Text(value,style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold)),Text(label,style:const TextStyle(color:Colors.grey,fontSize:12))])))); }

class StudentsPage extends StatefulWidget { const StudentsPage({super.key}); @override State<StudentsPage> createState()=>_StudentsPageState(); }
class _StudentsPageState extends State<StudentsPage>{
  String query=''; int? bus; late Future<List<Map<String,Object?>>> rows;
  @override void initState(){super.initState();reload();} void reload(){rows=context.read<AppState>().repo.students(query:query,vehicleId:bus);}
  @override Widget build(BuildContext context)=>PageFrame(title:'Students',subtitle:'Student profiles, bus groups, arrears and transfers',actions:[FilledButton.icon(onPressed:()=>editStudent(),icon:const Icon(Icons.add),label:const Text('Add student'))],child:Column(children:[
    Row(children:[Expanded(child:TextField(onChanged:(v){query=v;setState(reload);},decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Name, student ID or barcode...'))),const SizedBox(width:12),FutureBuilder(future:context.read<AppState>().repo.vehicles(),builder:(_,s)=>DropdownButton<int?>(value:bus,hint:const Text('All buses'),items:[const DropdownMenuItem(value:null,child:Text('All buses')),...?s.data?.map((v)=>DropdownMenuItem(value:v['id'] as int,child:Text('${v['vehicle_number']}')))],onChanged:(v)=>setState((){bus=v;reload();}))) ]),const SizedBox(height:14),
    Expanded(child:FutureBuilder<List<Map<String,Object?>>>(future:rows,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const EmptyState(Icons.school_outlined,'No students found');return Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final r=s.data![i];return ListTile(leading:CircleAvatar(child:Text('${r['name']}'.substring(0,1).toUpperCase())),title:Text('${r['name']}  •  ${r['student_code']}',style:const TextStyle(fontWeight:FontWeight.w600)),subtitle:Text('${r['vehicle_number']??'No bus'}  |  ${r['school']??''}  |  Grade ${r['grade']??'-'}'),trailing:Wrap(crossAxisAlignment:WrapCrossAlignment.center,children:[Text(money(r['outstanding']),style:TextStyle(color:(r['outstanding'] as num)>0?Colors.red:Colors.green,fontWeight:FontWeight.bold)),IconButton(onPressed:()=>editStudent(r),icon:const Icon(Icons.edit_outlined)),PopupMenuButton<String>(onSelected:(v)=>studentAction(v,r),itemBuilder:(_)=>[PopupMenuItem(value:'toggle',child:Text((r['is_active']==1)?'Deactivate':'Reactivate')),if(context.read<AppState>().canDelete)const PopupMenuItem(value:'delete',child:Text('Delete'))])]),onTap:()=>showStudent(r);};}));}))
  ]));
  Future<void> editStudent([Map<String,Object?>? row])async{final ok=await showDialog<bool>(context:context,builder:(_)=>StudentDialog(row:row));if(ok==true)setState(reload);}
  Future<void> studentAction(String a,Map<String,Object?> r)async{if(a=='toggle')await context.read<AppState>().repo.setStudentActive(r['id'] as int,r['is_active']!=1);else await context.read<AppState>().repo.deleteStudent(r['id'] as int);setState(reload);}
  void showStudent(Map<String,Object?> r)=>showDialog(context:context,builder:(_)=>AlertDialog(title:Text('${r['name']} — ${r['student_code']}'),content:SizedBox(width:520,child:FutureBuilder(future:context.read<AppState>().repo.ledger(r['id'] as int),builder:(_,s)=>ListView(shrinkWrap:true,children:[Text('Bus: ${r['vehicle_number']}\nSchool: ${r['school']}\nPickup: ${r['pickup_location']}\nWhatsApp: ${r['whatsapp_number']}\nMonthly fee: ${money(r['monthly_fee'])}\nOutstanding: ${money(r['outstanding'])}'),const SizedBox(height:18),const Text('Monthly ledger',style:TextStyle(fontWeight:FontWeight.bold)),...?s.data?.map((x)=>ListTile(dense:true,title:Text('${x['ledger_year']}-${('${x['ledger_month']}').padLeft(2,'0')}'),subtitle:Text('${x['status']}'),trailing:Text(money(x['balance_due']))))]))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]));
}

class StudentDialog extends StatefulWidget{final Map<String,Object?>? row;const StudentDialog({super.key,this.row});@override State<StudentDialog> createState()=>_StudentDialogState();}
class _StudentDialogState extends State<StudentDialog>{final form=GlobalKey<FormState>();late final Map<String,TextEditingController> c;int? vehicle;bool active=true;
  @override void initState(){super.initState();final r=widget.row??{};vehicle=r['vehicle_id'] as int?;active=r['is_active']!=0;c={for(final k in ['name','pickup_location','school','birth_year','grade','monthly_fee','whatsapp_number','phone_1','phone_2','previous_outstanding_balance'])k:TextEditingController(text:'${r[k]??''}')};}
  @override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.row==null?'Add student':'Edit student'),content:SizedBox(width:640,child:Form(key:form,child:SingleChildScrollView(child:Wrap(spacing:12,runSpacing:12,children:[field('name','Student name',required:true),FutureBuilder(future:context.read<AppState>().repo.vehicles(),builder:(_,s)=>SizedBox(width:290,child:DropdownButtonFormField<int>(value:vehicle,decoration:const InputDecoration(labelText:'Bus / Vehicle'),items:s.data?.map((v)=>DropdownMenuItem(value:v['id'] as int,child:Text('${v['vehicle_number']}'))).toList(),onChanged:(v)=>setState(()=>vehicle=v),validator:(v)=>v==null?'Select a vehicle':null))),field('pickup_location','Pickup / Drop location'),field('school','School'),field('birth_year','Birth year',numeric:true),field('grade','Grade'),field('monthly_fee','Monthly fee',numeric:true),field('previous_outstanding_balance','Opening arrears',numeric:true),field('whatsapp_number','WhatsApp number'),field('phone_1','Phone 1'),field('phone_2','Phone 2'),SizedBox(width:290,child:SwitchListTile(title:const Text('Active student'),value:active,onChanged:(v)=>setState(()=>active=v)))])))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);
  Widget field(String k,String label,{bool required=false,bool numeric=false})=>SizedBox(width:290,child:TextFormField(controller:c[k],keyboardType:numeric?TextInputType.number:null,decoration:InputDecoration(labelText:label),validator:(v)=>required&&v!.trim().isEmpty?'Required':null));
  Future<void> save()async{if(!form.currentState!.validate()||vehicle==null)return;final d=<String,Object?>{for(final e in c.entries)e.key:e.value.text.trim(),'vehicle_id':vehicle,'is_active':active?1:0,'monthly_fee':number(c['monthly_fee']!.text),'previous_outstanding_balance':number(c['previous_outstanding_balance']!.text)};d['birth_year']=int.tryParse(c['birth_year']!.text);if('${d['grade']}'.isEmpty&&d['birth_year']!=null)d['grade']='${DateTime.now().year-(d['birth_year'] as int)-5}';await context.read<AppState>().repo.saveStudent(d,widget.row?['id'] as int?);if(mounted)Navigator.pop(context,true);}
}

class PaymentsPage extends StatefulWidget{const PaymentsPage({super.key});@override State<PaymentsPage> createState()=>_PaymentsPageState();}
class _PaymentsPageState extends State<PaymentsPage>{int? student;final amount=TextEditingController();final notes=TextEditingController();String method='Cash';DateTime date=DateTime.now();
 @override Widget build(BuildContext context)=>PageFrame(title:'Receive Payment',subtitle:'Automatic oldest-month-first allocation',child:ListView(children:[Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Student and payment details',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:18),FutureBuilder(future:context.read<AppState>().repo.students(active:true),builder:(_,s)=>DropdownButtonFormField<int>(value:student,decoration:const InputDecoration(labelText:'Search / select student'),items:s.data?.map((r)=>DropdownMenuItem(value:r['id'] as int,child:Text('${r['student_code']} — ${r['name']} (${money(r['outstanding'])})'))).toList(),onChanged:(v)=>setState(()=>student=v))),const SizedBox(height:14),Row(children:[Expanded(child:TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount'))),const SizedBox(width:12),Expanded(child:DropdownButtonFormField(value:method,decoration:const InputDecoration(labelText:'Method'),items:['Cash','Card','Bank Transfer','Online','Other'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>method=v!)))]),const SizedBox(height:14),Row(children:[Expanded(child:TextField(controller:notes,decoration:const InputDecoration(labelText:'Remarks'))),const SizedBox(width:12),OutlinedButton.icon(onPressed:pickDate,icon:const Icon(Icons.calendar_month),label:Padding(padding:const EdgeInsets.all(12),child:Text(iso(date))))]),const SizedBox(height:20),FilledButton.icon(onPressed:pay,icon:const Icon(Icons.check_circle),label:const Padding(padding:EdgeInsets.all(12),child:Text('Confirm payment')))]))),const SizedBox(height:18),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Billing month',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:10),Text('Generate monthly fees for every active student. Skipped months are excluded.'),const SizedBox(height:12),FilledButton.tonalIcon(onPressed:generateMonth,icon:const Icon(Icons.calendar_view_month),label:const Text('Generate / advance billing month'))])))]));
 Future<void> pickDate()async{final d=await showDatePicker(context:context,firstDate:DateTime(2020),lastDate:DateTime(2100),initialDate:date);if(d!=null)setState(()=>date=d);}
 Future<void> pay()async{final value=number(amount.text);if(student==null||value<=0){toast('Select a student and enter an amount');return;}await context.read<AppState>().repo.makePayment(studentId:student!,amount:value,method:method,date:iso(date),notes:notes.text,userId:context.read<AppState>().user?['id'] as int?);amount.clear();notes.clear();setState(()=>student=null);toast('Payment saved successfully');}
 Future<void> generateMonth()async{final repo=context.read<AppState>().repo;var y=int.tryParse(await repo.setting('billing_year')??'')??DateTime.now().year;var m=int.tryParse(await repo.setting('billing_month')??'')??DateTime.now().month;m++;if(m==13){m=1;y++;}await repo.ensureLedger(y,m);toast('$y/$m billing generated');}
 void toast(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
}

class PaymentHistoryPage extends StatefulWidget{const PaymentHistoryPage({super.key});@override State<PaymentHistoryPage> createState()=>_PaymentHistoryPageState();}
class _PaymentHistoryPageState extends State<PaymentHistoryPage>{String q='';late Future<List<Map<String,Object?>>> rows;@override void initState(){super.initState();reload();}void reload()=>rows=context.read<AppState>().repo.payments(query:q);
 @override Widget build(BuildContext context)=>PageFrame(title:'Payment History',subtitle:'Receipts, dates, methods and reversals',child:Column(children:[TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Student, ID or receipt...'),onChanged:(v)=>setState((){q=v;reload();})),const SizedBox(height:14),Expanded(child:FutureBuilder(future:rows,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const EmptyState(Icons.receipt_long,'No payments found');return Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final r=s.data![i];return ListTile(leading:const CircleAvatar(child:Icon(Icons.receipt)),title:Text('${r['name']} • ${money(r['amount'])}'),subtitle:Text('${r['receipt_number']}  |  ${r['payment_date']}  |  ${r['payment_method']}  |  ${r['vehicle_number']??''}'),trailing:context.read<AppState>().canDelete?IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{await context.read<AppState>().repo.deletePayment(r['id'] as int);setState(reload);}):null);}))}))]));}

class VehiclesPage extends StatefulWidget{const VehiclesPage({super.key});@override State<VehiclesPage> createState()=>_VehiclesPageState();}
class _VehiclesPageState extends State<VehiclesPage>{String q='';late Future<List<Map<String,Object?>>> rows;@override void initState(){super.initState();reload();}void reload()=>rows=context.read<AppState>().repo.vehicles(query:q);
 @override Widget build(BuildContext context)=>PageFrame(title:'Vehicles',subtitle:'Documents, services, fuel and expiry tracking',actions:[FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Add vehicle'))],child:Column(children:[TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Vehicle number or driver...'),onChanged:(v)=>setState((){q=v;reload();})),const SizedBox(height:14),Expanded(child:FutureBuilder(future:rows,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const EmptyState(Icons.directions_bus,'No vehicles added');return GridView.builder(gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:380,mainAxisExtent:220,crossAxisSpacing:14,mainAxisSpacing:14),itemCount:s.data!.length,itemBuilder:(_,i){final r=s.data![i];return Card(child:Padding(padding:const EdgeInsets.all(17),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const CircleAvatar(child:Icon(Icons.directions_bus)),const SizedBox(width:10),Expanded(child:Text('${r['vehicle_number']}',style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold))),Chip(label:Text('${r['status']}'))]),const SizedBox(height:12),Text('Driver: ${r['driver_name']??'-'}'),Text('Phone: ${r['driver_phone']??'-'}'),Text('Students: ${r['student_count']} / ${r['seating_capacity']??'-'}'),const Spacer(),Row(children:[TextButton.icon(onPressed:()=>details(r),icon:const Icon(Icons.history),label:const Text('History')),const Spacer(),IconButton(onPressed:()=>edit(r),icon:const Icon(Icons.edit_outlined)),if(context.read<AppState>().canDelete)IconButton(onPressed:()async{await context.read<AppState>().repo.deleteVehicle(r['id'] as int);setState(reload);},icon:const Icon(Icons.delete_outline))])])));});}))]));
 Future<void> edit([Map<String,Object?>? r])async{final ok=await showDialog<bool>(context:context,builder:(_)=>VehicleDialog(row:r));if(ok==true)setState(reload);}void details(Map<String,Object?> r)=>showDialog(context:context,builder:(_)=>VehicleHistoryDialog(vehicle:r));}

class VehicleDialog extends StatefulWidget{final Map<String,Object?>? row;const VehicleDialog({super.key,this.row});@override State<VehicleDialog> createState()=>_VehicleDialogState();}
class _VehicleDialogState extends State<VehicleDialog>{late Map<String,TextEditingController> c;String type='Bus',usage='School',status='Active';@override void initState(){super.initState();final r=widget.row??{};type='${r['vehicle_type']??'Bus'}';usage='${r['usage_type']??'School'}';status='${r['status']??'Active'}';c={for(final k in ['vehicle_number','driver_name','driver_phone','chassis_number','seating_capacity','insurance_expiry','licence_expiry','revenue_licence_expiry','emission_test_expiry','notes'])k:TextEditingController(text:'${r[k]??''}')};}
 @override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.row==null?'Add vehicle':'Edit vehicle'),content:SizedBox(width:650,child:SingleChildScrollView(child:Wrap(spacing:12,runSpacing:12,children:[...c.entries.map((e)=>SizedBox(width:300,child:TextField(controller:e.value,decoration:InputDecoration(labelText:e.key.replaceAll('_',' '))))),drop('Vehicle type',type,['Bus','Van','Car','Other'],(v)=>type=v),drop('Usage',usage,['School','Hiring','Both'],(v)=>usage=v),drop('Status',status,['Active','Inactive','Maintenance'],(v)=>status=v)]))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);Widget drop(String l,String v,List<String>a,void Function(String)x)=>SizedBox(width:300,child:DropdownButtonFormField(value:v,decoration:InputDecoration(labelText:l),items:a.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(e)=>setState(()=>x(e!))));Future<void>save()async{if(c['vehicle_number']!.text.trim().isEmpty)return;final d=<String,Object?>{for(final e in c.entries)e.key:e.value.text.trim(),'vehicle_type':type,'usage_type':usage,'status':status};d['seating_capacity']=int.tryParse(c['seating_capacity']!.text);await context.read<AppState>().repo.saveVehicle(d,widget.row?['id'] as int?);if(mounted)Navigator.pop(context,true);}}

class VehicleHistoryDialog extends StatelessWidget{final Map<String,Object?> vehicle;const VehicleHistoryDialog({super.key,required this.vehicle});@override Widget build(BuildContext context)=>AlertDialog(title:Text('${vehicle['vehicle_number']} history'),content:SizedBox(width:750,height:500,child:DefaultTabController(length:2,child:Column(children:[const TabBar(tabs:[Tab(text:'Service history'),Tab(text:'Fuel log')]),Expanded(child:TabBarView(children:[HistoryList(future:context.read<AppState>().repo.vehicleServices(vehicle['id'] as int),builder:(r)=>'${r['service_date']} • ${r['service_type']} • ${money(r['cost'])} • ${r['odometer_reading']} km'),HistoryList(future:context.read<AppState>().repo.fuelLogs(vehicle['id'] as int),builder:(r)=>'${r['fuel_date']} • ${r['litres_filled']} L • ${money(r['fuel_cost'])} • ${((r['km_per_litre'] as num?)??0).toStringAsFixed(2)} km/L')]))]))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]);}
class HistoryList extends StatelessWidget{final Future<List<Map<String,Object?>>> future;final String Function(Map<String,Object?>) builder;const HistoryList({super.key,required this.future,required this.builder});@override Widget build(BuildContext context)=>FutureBuilder(future:future,builder:(_,s)=>!s.hasData?const Center(child:CircularProgressIndicator()):s.data!.isEmpty?const EmptyState(Icons.history,'No records'):ListView.builder(itemCount:s.data!.length,itemBuilder:(_,i)=>ListTile(title:Text(builder(s.data![i])))));}

class HiringPage extends StatefulWidget{const HiringPage({super.key});@override State<HiringPage> createState()=>_HiringPageState();}
class _HiringPageState extends State<HiringPage>{String q='';late Future<List<Map<String,Object?>>> rows;@override void initState(){super.initState();reload();}void reload()=>rows=context.read<AppState>().repo.hiring(query:q);
 @override Widget build(BuildContext context)=>PageFrame(title:'Hiring / Trips',subtitle:'Bookings, balances, expenses and profit',actions:[FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('New booking'))],child:Column(children:[TextField(decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Customer, destination or invoice...'),onChanged:(v)=>setState((){q=v;reload();})),const SizedBox(height:14),Expanded(child:FutureBuilder(future:rows,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(s.data!.isEmpty)return const EmptyState(Icons.route,'No bookings found');return Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final r=s.data![i];return ListTile(leading:CircleAvatar(child:Text('${r['booking_status']}'.substring(0,1))),title:Text('${r['customer_name']} → ${r['destination']}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${r['invoice_number']} | ${r['trip_date']} | ${r['vehicle_number']} | ${r['payment_status']}'),trailing:Wrap(crossAxisAlignment:WrapCrossAlignment.center,children:[Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text(money(r['trip_charge']),style:const TextStyle(fontWeight:FontWeight.bold)),Text('Profit ${money(r['profit'])}',style:const TextStyle(fontSize:11,color:Colors.green))]),IconButton(onPressed:()=>edit(r),icon:const Icon(Icons.edit_outlined)),IconButton(onPressed:()=>expenses(r),icon:const Icon(Icons.wallet_outlined))]));}))}))]));
 Future<void> edit([Map<String,Object?>? r])async{final ok=await showDialog<bool>(context:context,builder:(_)=>HiringDialog(row:r));if(ok==true)setState(reload);}void expenses(Map<String,Object?> r)=>showDialog(context:context,builder:(_)=>ExpenseDialog(hiring:r));}

class HiringDialog extends StatefulWidget{final Map<String,Object?>? row;const HiringDialog({super.key,this.row});@override State<HiringDialog> createState()=>_HiringDialogState();}
class _HiringDialogState extends State<HiringDialog>{late Map<String,TextEditingController> c;int? vehicle;String booking='Upcoming',payment='Pending';@override void initState(){super.initState();final r=widget.row??{};vehicle=r['vehicle_id'] as int?;booking='${r['booking_status']??'Upcoming'}';payment='${r['payment_status']??'Pending'}';c={for(final k in ['customer_name','customer_mobile','customer_whatsapp','customer_address','driver_name','trip_date','pickup_location','destination','trip_charge','advance_payment','notes'])k:TextEditingController(text:'${r[k]??(k=='trip_date'?iso(DateTime.now()):'')}')};}
 @override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.row==null?'New booking':'Edit booking'),content:SizedBox(width:660,child:SingleChildScrollView(child:Wrap(spacing:12,runSpacing:12,children:[...c.entries.map((e)=>SizedBox(width:305,child:TextField(controller:e.value,decoration:InputDecoration(labelText:e.key.replaceAll('_',' '))))),FutureBuilder(future:context.read<AppState>().repo.vehicles(),builder:(_,s)=>SizedBox(width:305,child:DropdownButtonFormField<int>(value:vehicle,decoration:const InputDecoration(labelText:'Vehicle'),items:s.data?.map((v)=>DropdownMenuItem(value:v['id'] as int,child:Text('${v['vehicle_number']}'))).toList(),onChanged:(v)=>setState(()=>vehicle=v))),drop('Booking status',booking,['Upcoming','Running','Completed','Cancelled'],(v)=>booking=v),drop('Payment status',payment,['Paid','Advance Paid','Pending'],(v)=>payment=v)]))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:save,child:const Text('Save'))]);Widget drop(String l,String v,List<String>a,void Function(String)x)=>SizedBox(width:305,child:DropdownButtonFormField(value:v,decoration:InputDecoration(labelText:l),items:a.map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(e)=>setState(()=>x(e!))));Future<void>save()async{if(vehicle==null||c['customer_name']!.text.isEmpty)return;final d=<String,Object?>{for(final e in c.entries)e.key:e.value.text.trim(),'vehicle_id':vehicle,'booking_status':booking,'payment_status':payment,'trip_charge':number(c['trip_charge']!.text),'advance_payment':number(c['advance_payment']!.text)};try{await context.read<AppState>().repo.saveHiring(d,widget.row?['id'] as int?);if(mounted)Navigator.pop(context,true);}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$e')));}}}

class ExpenseDialog extends StatefulWidget{final Map<String,Object?> hiring;const ExpenseDialog({super.key,required this.hiring});@override State<ExpenseDialog> createState()=>_ExpenseDialogState();}
class _ExpenseDialogState extends State<ExpenseDialog>{String type='Fuel';final amount=TextEditingController(),notes=TextEditingController();late Future<List<Map<String,Object?>>> rows;@override void initState(){super.initState();reload();}void reload()=>rows=context.read<AppState>().repo.expenses(widget.hiring['id'] as int);@override Widget build(BuildContext context)=>AlertDialog(title:Text('Expenses — ${widget.hiring['invoice_number']}'),content:SizedBox(width:620,height:440,child:Column(children:[Row(children:[Expanded(child:DropdownButtonFormField(value:type,items:['Fuel','Driver Allowance','Toll','Parking','Other'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>type=v!))),const SizedBox(width:8),Expanded(child:TextField(controller:amount,decoration:const InputDecoration(labelText:'Amount'))),const SizedBox(width:8),IconButton.filled(onPressed:add,icon:const Icon(Icons.add))]),const SizedBox(height:12),TextField(controller:notes,decoration:const InputDecoration(labelText:'Notes')),const SizedBox(height:12),Expanded(child:HistoryList(future:rows,builder:(r)=>'${r['expense_type']} • ${money(r['amount'])} • ${r['notes']??''}'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]);Future<void>add()async{await context.read<AppState>().repo.addExpense({'hiring_id':widget.hiring['id'],'expense_type':type,'amount':number(amount.text),'notes':notes.text});amount.clear();notes.clear();setState(reload);}}

class MessagesPage extends StatefulWidget{const MessagesPage({super.key});@override State<MessagesPage> createState()=>_MessagesPageState();}
class _MessagesPageState extends State<MessagesPage>{int? bus;final message=TextEditingController(text:'හිතවත් දෙමාපියනි, මෙම මාසයේ පාසල් ප්‍රවාහන ගාස්තුව ගෙවීමට කාරුණික වන්න. ස්තූතියි.');
 @override Widget build(BuildContext context)=>PageFrame(title:'Messages',subtitle:'Bus-wise WhatsApp payment reminders',child:ListView(children:[Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Broadcast filters',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:15),FutureBuilder(future:context.read<AppState>().repo.vehicles(),builder:(_,s)=>DropdownButtonFormField<int>(value:bus,decoration:const InputDecoration(labelText:'Bus'),items:s.data?.map((v)=>DropdownMenuItem(value:v['id'] as int,child:Text('${v['vehicle_number']}'))).toList(),onChanged:(v)=>setState(()=>bus=v))),const SizedBox(height:14),TextField(controller:message,maxLines:5,decoration:const InputDecoration(labelText:'Message')),const SizedBox(height:16),FilledButton.icon(onPressed:send,icon:const Icon(Icons.send),label:const Text('Open WhatsApp messages'))])))]));
 Future<void>send()async{if(bus==null)return;final rows=await context.read<AppState>().repo.students(vehicleId:bus,active:true);var opened=0;for(final r in rows){final phone='${r['whatsapp_number']??''}'.replaceAll(RegExp(r'[^0-9]'),'');if(phone.isEmpty)continue;final normalized=phone.startsWith('0')?'94${phone.substring(1)}':phone;final uri=Uri.parse('https://wa.me/$normalized?text=${Uri.encodeComponent(message.text.replaceAll('{name}','${r['name']}'))}');if(await canLaunchUrl(uri)){await launchUrl(uri,mode:LaunchMode.externalApplication);opened++;break;}}if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(opened==0?'No valid WhatsApp numbers':'Opened first message. Confirm send, then continue per student.')));}
}

class ReportsPage extends StatefulWidget{const ReportsPage({super.key});@override State<ReportsPage> createState()=>_ReportsPageState();}
class _ReportsPageState extends State<ReportsPage>{
 final defs=const [('Active Students','students'),('Payment History','payments'),('Vehicles','vehicles'),('Hiring & Profit','hiring'),('Audit Log','audit')];
 @override Widget build(BuildContext context)=>PageFrame(title:'Reports',subtitle:'Live reports and CSV exports',child:GridView.builder(gridDelegate:const SliverGridDelegateWithMaxCrossAxisExtent(maxCrossAxisExtent:360,mainAxisExtent:155,crossAxisSpacing:14,mainAxisSpacing:14),itemCount:defs.length,itemBuilder:(_,i)=>Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(Icons.description_outlined,color:Theme.of(context).colorScheme.primary),const Spacer(),Text(defs[i].$1,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Row(children:[const Text('CSV / Excel compatible',style:TextStyle(color:Colors.grey,fontSize:11)),const Spacer(),IconButton.filledTonal(onPressed:()=>export(defs[i]),icon:const Icon(Icons.download))])]))));
 Future<void>export((String,String) def)async{final repo=context.read<AppState>().repo;final rows=switch(def.$2){'students'=>await repo.students(),'payments'=>await repo.payments(),'vehicles'=>await repo.vehicles(),'hiring'=>await repo.hiring(),_=>await repo.audit()};if(rows.isEmpty)return;final csv=const ListToCsvConverter().convert([rows.first.keys.toList(),...rows.map((r)=>r.values.toList())]);final dir=await getApplicationDocumentsDirectory();final folder=Directory(p.join(dir.path,'Nethsara Reports'));await folder.create(recursive:true);final file=File(p.join(folder.path,'${def.$2}_${iso(DateTime.now())}.csv'));await file.writeAsString(csv);if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Saved: ${file.path}')));}
}

class SettingsPage extends StatefulWidget{const SettingsPage({super.key});@override State<SettingsPage> createState()=>_SettingsPageState();}
class _SettingsPageState extends State<SettingsPage>{late Future<Map<String,String>> future;final keys=['company_name','company_address','company_phone','company_whatsapp','company_email','receipt_prefix','invoice_prefix'];Map<String,TextEditingController> c={};@override void initState(){super.initState();future=context.read<AppState>().repo.settings();}
 @override Widget build(BuildContext context)=>PageFrame(title:'Settings',subtitle:'Company, appearance, users and database',child:FutureBuilder(future:future,builder:(_,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());if(c.isEmpty)c={for(final k in keys)k:TextEditingController(text:s.data![k]??'')};return ListView(children:[Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Company profile',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:15),Wrap(spacing:12,runSpacing:12,children:c.entries.map((e)=>SizedBox(width:310,child:TextField(controller:e.value,decoration:InputDecoration(labelText:e.key.replaceAll('_',' '))))).toList()),const SizedBox(height:16),FilledButton.icon(onPressed:save,icon:const Icon(Icons.save),label:const Text('Save settings'))]))),const SizedBox(height:14),Card(child:Column(children:[SwitchListTile(title:const Text('Dark mode'),subtitle:const Text('Change application appearance'),value:context.watch<AppState>().darkMode,onChanged:context.read<AppState>().setDark),const Divider(height:1),ListTile(leading:const Icon(Icons.backup),title:const Text('Backup database'),subtitle:const Text('Save a dated copy in Documents/Nethsara Backups'),trailing:const Icon(Icons.chevron_right),onTap:backup),ListTile(leading:const Icon(Icons.restore),title:const Text('Restore database'),subtitle:const Text('A safety backup is created first'),trailing:const Icon(Icons.chevron_right),onTap:restore),ListTile(leading:const Icon(Icons.system_update_alt),title:const Text('Import bundled v3.9 database'),subtitle:const Text('Use the original database included with this project'),trailing:const Icon(Icons.chevron_right),onTap:legacy)])),const SizedBox(height:14),if(context.read<AppState>().isAdmin)Card(child:ListTile(leading:const Icon(Icons.admin_panel_settings),title:const Text('Administrator tools'),subtitle:const Text('User/role management and audit logs are database-backed. Add a dedicated UI here if multiple staff accounts are needed.')))]);}));
 Future<void>save()async{await context.read<AppState>().repo.saveSettings({for(final e in c.entries)e.key:e.value.text});toast('Settings saved');}Future<void>backup()async{final path=await context.read<AppState>().db.backup();toast('Backup saved: $path');}Future<void>restore()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['db']);if(r?.files.single.path!=null){await context.read<AppState>().db.restore(r!.files.single.path!);toast('Database restored. Restart the app.');}}Future<void>legacy()async{final path=await context.read<AppState>().db.extractBundledLegacy();await context.read<AppState>().db.restore(path);toast('v3.9 database imported. Restart the app.');}void toast(String x)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));
}

class UsersPage extends StatefulWidget{const UsersPage({super.key});@override State<UsersPage> createState()=>_UsersPageState();}
class _UsersPageState extends State<UsersPage>{late Future<List<Map<String,Object?>>> rows;@override void initState(){super.initState();reload();}void reload()=>rows=context.read<AppState>().repo.users();@override Widget build(BuildContext context){if(!context.read<AppState>().isAdmin)return const PageFrame(title:'Users',child:EmptyState(Icons.lock,'Administrator access required'));return PageFrame(title:'Users & Roles',subtitle:'Administrator, Manager and Cashier access',actions:[FilledButton.icon(onPressed:add,icon:const Icon(Icons.person_add),label:const Text('Add user'))],child:FutureBuilder(future:rows,builder:(_,s)=>!s.hasData?const Center(child:CircularProgressIndicator()):Card(child:ListView.separated(itemCount:s.data!.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final r=s.data![i];return SwitchListTile(value:r['is_active']==1,onChanged:(v)async{await context.read<AppState>().repo.setUserActive(r['id'] as int,v);setState(reload);},secondary:const CircleAvatar(child:Icon(Icons.person)),title:Text('${r['full_name']} (${r['username']})'),subtitle:Text('${r['role']} • Last login: ${r['last_login_at']??'Never'}'));}))));}
 Future<void>add()async{final u=TextEditingController(),p=TextEditingController(),n=TextEditingController();String role='Cashier';final ok=await showDialog<bool>(context:context,builder:(dialogContext)=>StatefulBuilder(builder:(_,setLocal)=>AlertDialog(title:const Text('Add user'),content:SizedBox(width:420,child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Full name')),const SizedBox(height:10),TextField(controller:u,decoration:const InputDecoration(labelText:'Username')),const SizedBox(height:10),TextField(controller:p,obscureText:true,decoration:const InputDecoration(labelText:'Password')),const SizedBox(height:10),DropdownButtonFormField(value:role,items:['Administrator','Manager','Cashier'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setLocal(()=>role=v!))])),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(dialogContext,true),child:const Text('Create'))])));if(ok==true){await context.read<AppState>().repo.createUser(u.text,p.text,n.text,role);setState(reload);}}
}
